ktor:
  application:
    modules:
      - com.emiliagomez.api.ApplicationKt.module
  deployment:
    port: 8081
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password